[agent]
  interval = "30s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "2s"
  hostname = "factory-gateway-01"
  omit_hostname = false

# ------------------------------------------------------------------------------
# OUTPUTS: InfluxDB v2
# ------------------------------------------------------------------------------
[[outputs.influxdb_v2]]
  urls = ["https://us-east-1-1.aws.cloud2.influxdata.com"]
  token = "${INFLUX_TOKEN2}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET2}"

    ## The most important fix for "Context Deadline Exceeded"
  timeout = "30s"

  ## Optional: Use gzip compression to reduce bandwidth usage
  content_encoding = "gzip"

# --- MACHINE TELEMETRY ---
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["factory/+/+/telemetry"]
  name_override = "machine_telemetry"
  data_format = "json_v2"
  [[inputs.mqtt_consumer.json_v2]]
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"
      # Added unit tags here
      tags = ["tenant", "plant", "machine", "type", "sensor_id", "seq_id", "rpm_unit", "temp_unit", "vib_unit"]
      included_keys = ["rpm", "temp", "vib"]

# --- PRODUCTION METRICS ---
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["factory/+/+/production"]
  name_override = "production_metrics"
  data_format = "json_v2"
  [[inputs.mqtt_consumer.json_v2]]
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"
      tags = ["tenant", "plant", "machine", "sensor_id", "seq_id", "weight_unit"]
      included_keys = ["in_kg", "out_kg","yield_target"]

# --- ENERGY METRICS ---
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["factory/+/+/energy"]
  name_override = "energy_metrics"
  data_format = "json_v2"
  [[inputs.mqtt_consumer.json_v2]]
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"
      tags = ["tenant", "plant", "machine", "sensor_id", "seq_id", "kwh_unit", "kw_unit"]
      included_keys = ["kwh", "kw"]

# --- CONDITION METRICS ---
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["factory/+/+/condition"]
  name_override = "condition_metrics"
  data_format = "json_v2"
  [[inputs.mqtt_consumer.json_v2]]
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"
      tags = ["tenant", "plant", "machine", "sensor_id", "seq_id", "brg_temp_unit", "lub_unit"]
      included_keys = ["brg_temp", "lub_lvl"]