[agent]
  interval = "10s"

# Input: Subscribe to your Mosquitto broker
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]

  # Subscribe to the entire hierarchy
  topics = ["+/+/+/+/+/telemetry"]

  data_format = "json"
  # Define how to "explode" the topic into InfluxDB Tags
  # Topic: domain/tenant_id/plant_id/area/asset_id/message_type
  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "+/+/+/+/+/+"
    measurement = "_/_/_/_/_/measurement" # Takes 'telemetry' as the measurement name
    tags = "domain/tenant/plant/area/asset/_"



# Output: Send to InfluxDB Cloud
[[outputs.influxdb_v2]]
  urls = ["https://us-east-1-1.aws.cloud2.influxdata.com"] # Change to your Cloud Region URL
  token = "${INFLUX_TOKEN1}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET1}"
  # Only send data if the tenant tag matches
  [outputs.influxdb_v2.tagpass]
    tenant = ["tenant_alpha"]

 # Output: Send to InfluxDB Cloud
[[outputs.influxdb_v2]]
  urls = ["https://us-east-1-1.aws.cloud2.influxdata.com"] # Change to your Cloud Region URL
  token = "${INFLUX_TOKEN2}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET2}"

  # Only send data if the tenant tag matches
  [outputs.influxdb_v2.tagpass]
    tenant = ["tenant_beta"]